### PR TITLE
Stroke width fix for dashes & stroking example page

### LINKED ISSUE #14: Stroke dash length and space between dashes do not match other platforms
``` JSX
<Svg width="200" height="60">
  <Rect
    x="5%"
    y="5%"
    width="90%"
    height="90%"
    fill="rgb(0,0,255)"
    strokeWidth="3"
    stroke="rgb(0,0,0)"
    strokeDasharray="5,10"
  />
</Svg>
```

Expected:
image

Actual:
image

### PR DESCRIPTION
**Pull request by agniuks**
fixes #14 
dashArray example in stroking example page doesn't match other platforms, stroke will need some further work - using #17 to track that.

### CODE REVIEW

File: windows/RNSVG/Utils.h [hunk 1]
```diff
@@ -19,11 +19,11 @@ using namespace Windows::UI::Text;
 namespace winrt::RNSVG {
 struct Utils {
  public:
-  static std::vector<float> GetValueArray(IVector<SVGLength> const &value) {
+  static std::vector<float> GetAdjustedStrokeArray(IVector<SVGLength> const &value, SVGLength StrokeWidth) {
     std::vector<float> result;
 
     for (auto const &item : value) {
-      result.push_back(item.Value());
+      result.push_back(item.Value() / StrokeWidth.Value());
```
Comment (marlenecota) [inline windows/RNSVG/Utils.h]: Add comment why we're diving the by strokewidth with a link to win2d docs.

File: windows/RNSVG/RenderableView.cpp [hunk 2]
```diff
@@ -222,7 +222,7 @@ void RenderableView::Render(
     strokeStyle.LineJoin(StrokeLineJoin());
     strokeStyle.DashOffset(StrokeDashOffset());
     strokeStyle.MiterLimit(StrokeMiterLimit());
-    strokeStyle.CustomDashStyle(Utils::GetValueArray(StrokeDashArray()));
+    strokeStyle.CustomDashStyle(Utils::GetAdjustedStrokeArray(StrokeDashArray(), StrokeWidth()));
```
Comment (marlenecota) [inline windows/RNSVG/RenderableView.cpp]: Pass in the adjusted strokeWidth as a float.

float strokeWidth{Utils::GetSvgLengthValue(StrokeWidth(), canvas.Size().Width)};

File: windows/RNSVG/RenderableView.cpp [hunk 3]
```diff
@@ -222,7 +222,7 @@ void RenderableView::Render(
...
 
     auto const &stroke{Utils::GetCanvasBrush(StrokeBrushId(), Stroke(), SvgRoot(), geometry, resourceCreator)};
     session.DrawGeometry(geometry, stroke, StrokeWidth().Value(), strokeStyle);
```
Comment (marlenecota) [inline windows/RNSVG/RenderableView.cpp]: Replace StrokeWidth().Value() with the new adjusted stroke width variable.

**Review by marlenecota — CHANGES_REQUESTED** [review]

**Review by marlenecota — APPROVED** [review]
